'use strict';
const fs=require('node:fs'),assert=require('node:assert/strict'),vm=require('node:vm');
const {buildCameronHTML,checkedBank}=require('./real-estate-schools.js');
const html=fs.readFileSync('real-estate-quiz.html','utf8');
const originalMatch=html.match(/^const BANK = (\[.*\]);$/m);assert(originalMatch,'Gold Coast bank exists');
const original=JSON.parse(originalMatch[1]);assert.equal(original.length,271);
const fixture={version:1,school:'cameron',questions:[{id:'ca-Q900',question:'Fixture only: choose the first option.',options:{a:'First',b:'Second',c:'Third',d:'Fourth'},finalAnswer:'a',source:'Cameron Academy',sourceRef:'Q900',topic:'Fixture',ch:0}],pending:[{id:'ca-Q901',reason:'No captured answer.'}]};
const transformed=buildCameronHTML(html,fixture);
assert(!transformed.includes('book-text.js'),'No Gold Coast textbook is loaded in Cameron');
assert(!transformed.includes('script.google.com'),'Cameron does not contact Gold Coast sync');
assert(!transformed.includes("'reqz_hist'"),'No shared history key');
assert(transformed.includes('reqz_cameron_hist'),'Cameron has its own history');
assert(!transformed.includes(original[0].question),'Original bank is not duplicated into Cameron');
const m=transformed.match(/^const BANK = (\[.*\]);$/m);assert.deepEqual(JSON.parse(m[1]),fixture.questions);
for(const match of transformed.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g))new vm.Script(match[1]);
assert.throws(()=>checkedBank({...fixture,questions:[{...fixture.questions[0],finalAnswer:null}]}));
assert.throws(()=>checkedBank({...fixture,pending:[{id:'ca-Q900'}]}));
assert.throws(()=>buildCameronHTML(html.replace('const BANK = [','const CHANGED_BANK = ['),fixture));
const xss=buildCameronHTML(html,{...fixture,questions:[{...fixture.questions[0],question:'</script><script>throw Error("unsafe")</script>'}]});
assert(!xss.includes('<script>throw Error("unsafe")'),'Imported text cannot close a script');
assert.equal(fs.readFileSync('real-estate-quiz.html','utf8'),html,'Original quiz remains byte-identical');
console.log('PASS: original 271 questions; private bank adapter; isolated storage; no wrong-school textbook/sync; missing-answer rejection; source guards; JavaScript parsing; script-text escaping.');
const {mergeCameronSections,cameronSectionsRuntime}=require('./real-estate-schools-sections.js');
const pack={version:1,school:'cameron',section:{id:'FLREEPS3',title:'Section 3',number:3,total:1},questions:[{...fixture.questions[0],id:'ca-Q903',sourceRef:'Q903',sectionId:'FLREEPS3',sourceQuestion:1,courseExplanation:'Fixture explanation.'}]};
const merged=mergeCameronSections(fixture,pack,checkedBank);
assert.equal(merged.questions.length,2);assert.equal(merged.pending.length,1);
assert.equal(merged.questions[0].id,fixture.questions[0].id);assert.equal(merged.questions[0].sectionId,'FLREEPS1');
assert.deepEqual(merged.sections.map(s=>s.id),['FLREEPS1','FLREEPS3']);
assert.equal(fixture.questions[0].sectionId,undefined,'Original source is not mutated');
assert.throws(()=>mergeCameronSections(fixture,{...pack,questions:[{...pack.questions[0],id:'ca-Q900'}]},checkedBank));
assert.throws(()=>mergeCameronSections(fixture,{...pack,questions:[{...pack.questions[0],courseExplanation:''}]},checkedBank));
new vm.Script('('+cameronSectionsRuntime.toString()+')();');
console.log('PASS: section merge preserves original ids; unique source ordinals; incomplete answers excluded; named sections 1/3; course provenance required.');
