'use strict';
const assert=require('node:assert/strict');
const {checkedBank}=require('./real-estate-schools.js');
const {mergeCameronSections}=require('./real-estate-schools-sections.js');
const q=id=>({id:'ca-Q'+id,question:'Synthetic fixture',options:{a:'A',b:'B',c:'C',d:'D'},finalAnswer:'a',courseExplanation:'Fixture explanation.'});
const base={version:1,school:'cameron',questions:[q(900)],pending:[{id:'ca-Q901',reason:'Answer not captured.'}]};
const pack=(number,id)=>({version:1,school:'cameron',section:{id:'FLREEPS'+number,number,title:'Section '+number,total:1},questions:[{...q(id),sectionId:'FLREEPS'+number,sourceQuestion:1}],pending:[]});
const three=pack(3,903),four=pack(4,904);
const original=JSON.stringify(base);
const merged3=mergeCameronSections(base,three,checkedBank),saved3=JSON.stringify(merged3);
four.sourceAttempts=[{sectionId:'FLREEPS3',correct:0,total:1,duration:'00:00:27',duplicateQuestions:1,importAsAppProgress:false},{sectionId:'FLREEPS4',correct:1,total:1,duration:'00:02:15',importAsAppProgress:false}];
const merged4=mergeCameronSections(merged3,four,checkedBank);
assert.deepEqual(merged4.sections.map(s=>s.id),['FLREEPS1','FLREEPS3','FLREEPS4']);
assert.deepEqual(merged4.questions.map(x=>x.sectionId),['FLREEPS1','FLREEPS3','FLREEPS4']);
assert.deepEqual(merged4.questions.slice(0,2),merged3.questions,'Existing IDs, answers and source metadata preserved');
assert.equal(merged4.questions.length,3,'Duplicate source attempt adds no questions');
assert.equal(merged4.pending.length,1);
assert.equal(merged4.sourceAttempts.length,2);
assert.equal(JSON.stringify(base),original);assert.equal(JSON.stringify(merged3),saved3);
assert.throws(()=>mergeCameronSections(merged4,four,checkedBank),/already imported/);
assert.throws(()=>mergeCameronSections(merged3,{...four,questions:[{...four.questions[0],id:'ca-Q901'}]},checkedBank),/Duplicate/);
assert.throws(()=>mergeCameronSections(merged3,{...four,sourceAttempts:[{...four.sourceAttempts[0],importAsAppProgress:true}]},checkedBank),/metadata/);
assert.throws(()=>mergeCameronSections(merged3,{...four,section:{...four.section,number:5}},checkedBank),/metadata/);
assert.throws(()=>mergeCameronSections(merged3,{...four,questions:[{...four.questions[0],courseExplanation:''}]},checkedBank),/metadata/);
const truncated={...four,questions:[{...four.questions[0],courseExplanation:'Incomplete source fragment',sourceWarning:'Source ends mid-sentence.'}]};
assert.equal(mergeCameronSections(merged3,truncated,checkedBank).questions.at(-1).sourceWarning,'Source ends mid-sentence.');
console.log('PASS: sequential Sections 1/3/4 preserve IDs and section provenance; repeat attempts add no questions or practice history; pending IDs protected; missing metadata rejected; incomplete explanation warning retained.');
