'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs');
const {checkedBank}=require('./real-estate-schools.js');
const {mergeCameronSections}=require('./real-estate-schools-sections.js');
const q=id=>({id:'ca-Q'+id,question:'Synthetic fixture '+id,options:{a:'A',b:'B',c:'C',d:'D'},finalAnswer:'a',courseExplanation:'Fixture only.'});
const pack=(n,id)=>({version:1,school:'cameron',section:{id:'FLREEPS'+n,number:n,title:'Section '+n,total:1},questions:[{...q(id),sectionId:'FLREEPS'+n,sourceQuestion:1}],pending:[]});
let prior={version:1,school:'cameron',questions:[q(900)],pending:[{id:'ca-Q901'}]};
for(const n of [3,4,5])prior=mergeCameronSections(prior,pack(n,900+n),checkedBank);
const snapshot=JSON.stringify(prior),six=pack(6,906);
six.questions[0].sourceWarning='Conflicting source: preserve the marked answer and conflicting explanation.';
six.questions[0].courseExplanation='This synthetic explanation names a different answer.';
six.sourceAttempts=[{sectionId:'FLREEPS6',correct:1,total:1,duration:'00:00:30',importAsAppProgress:false}];
const merged=mergeCameronSections(prior,six,checkedBank);
assert.deepEqual(merged.sections.map(s=>s.id),['FLREEPS1','FLREEPS3','FLREEPS4','FLREEPS5','FLREEPS6']);
assert.deepEqual(merged.questions.slice(0,-1),prior.questions);assert.deepEqual(merged.pending,prior.pending);
assert.equal(JSON.stringify(prior),snapshot);assert.equal(merged.questions.length,prior.questions.length+1);
assert.equal(merged.questions.at(-1).sourceWarning,six.questions[0].sourceWarning);
assert.equal(merged.questions.at(-1).courseExplanation,six.questions[0].courseExplanation);
assert.equal(merged.questions.at(-1).finalAnswer,'a');assert.equal(merged.sourceAttempts[0].importAsAppProgress,false);
assert.throws(()=>mergeCameronSections(merged,six,checkedBank),/already imported/);
assert.throws(()=>mergeCameronSections(prior,{...six,questions:[{...six.questions[0],id:'ca-Q901'}]},checkedBank),/Duplicate/);
assert.throws(()=>mergeCameronSections(prior,{...six,sourceAttempts:[{...six.sourceAttempts[0],importAsAppProgress:true}]},checkedBank),/Source attempt/);
const envelope=JSON.parse(fs.readFileSync('cameron-section-6.enc.json','utf8'));
assert.equal(envelope.ready,17);assert.equal(envelope.pending,0);assert.equal(envelope.algorithm,'AES-GCM');
console.log('PASS: Section 6 additive; all prior IDs/pending preserved; marked answer, conflicting explanation and warning retained; source attempts not app progress; 17-question envelope.');
