'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs');
const {checkedBank}=require('./real-estate-schools.js');
const {mergeCameronSections}=require('./real-estate-schools-sections.js');
const q=id=>({id:'ca-Q'+id,question:'Synthetic import fixture '+id,options:{a:'A',b:'B',c:'C',d:'D'},finalAnswer:'a',courseExplanation:'Fixture only.'});
const pack=(n,id)=>({version:1,school:'cameron',section:{id:'FLREEPS'+n,number:n,title:'Section '+n,total:1},questions:[{...q(id),sectionId:'FLREEPS'+n,sourceQuestion:1}],pending:[]});
let previous={version:1,school:'cameron',questions:[q(900)],pending:[{id:'ca-Q901'}]};
for(const n of [3,4])previous=mergeCameronSections(previous,pack(n,900+n),checkedBank);
const snapshot=JSON.stringify(previous),five=pack(5,905);
five.sourceAttempts=[{sectionId:'FLREEPS4',correct:0,total:1,duplicateQuestions:1,importAsAppProgress:false},{sectionId:'FLREEPS5',correct:1,total:1,importAsAppProgress:false}];
const merged=mergeCameronSections(previous,five,checkedBank);
assert.deepEqual(merged.sections.map(s=>s.id),['FLREEPS1','FLREEPS3','FLREEPS4','FLREEPS5']);
assert.deepEqual(merged.questions.slice(0,-1),previous.questions);
assert.equal(merged.questions.length,previous.questions.length+1);
assert.deepEqual(merged.pending,previous.pending);
assert.equal(JSON.stringify(previous),snapshot);
assert.equal(merged.sourceAttempts.length,2);
assert.throws(()=>mergeCameronSections(merged,five,checkedBank),/already imported/);
assert.throws(()=>mergeCameronSections(previous,{...five,questions:[{...five.questions[0],id:'ca-Q901'}]},checkedBank),/Duplicate/);
const encrypted=JSON.parse(fs.readFileSync('cameron-section-5.enc.json','utf8'));
assert.equal(encrypted.ready,19);assert.equal(encrypted.pending,0);assert.equal(encrypted.algorithm,'AES-GCM');
console.log('PASS: Section 5 is additive; prior questions/pending unchanged; repeated Section 4 attempt adds no questions; repeat import rejected; 19-question encrypted envelope.');
